name: build-docker-image

on: [push, workflow_dispatch]

jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ksssomesh12
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        id: cache_docker_layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-tgmb-base-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-tgmb-base-

      - name: Build-Push Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.setup_buildx.outputs.name }}
          target: base
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          tags: ghcr.io/ksssomesh12/tgmb-beta:base

      - name: Docker Image Digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}

      - name: Move Docker Layer Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-api:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ksssomesh12
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        id: cache_docker_layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-tgmb-api-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-tgmb-api-

      - name: Build-Push Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.setup_buildx.outputs.name }}
          target: api
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          tags: ghcr.io/ksssomesh12/tgmb-beta:api

      - name: Docker Image Digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}

      - name: Move Docker Layer Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-mega:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ksssomesh12
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        id: cache_docker_layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-tgmb-mega-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-tgmb-mega-

      - name: Build-Push Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.setup_buildx.outputs.name }}
          target: mega
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          tags: ghcr.io/ksssomesh12/tgmb-beta:mega

      - name: Docker Image Digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}

      - name: Move Docker Layer Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  build-app:
    runs-on: ubuntu-latest
    needs: [build-base, build-api, build-mega]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ksssomesh12
          password: ${{ secrets.GH_PACKAGES_TOKEN }}

      - name: Setup Docker Buildx
        id: setup_buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker Layers
        id: cache_docker_layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-tgmb-app-${{ github.sha }}
          restore-keys: ${{ runner.os }}-buildx-tgmb-app-

      - name: Get Branch/Tag Ref
        id: get_ref
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"

      - name: Build-Push Docker Image
        id: docker_build_push
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.setup_buildx.name }}
          target: app
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          push: true
          tags: |
            ghcr.io/ksssomesh12/tgmb-beta:${{ github.sha }}
            ghcr.io/ksssomesh12/tgmb-beta:${{ steps.get_ref.outputs.ref }}

      - name: Docker Image Digest
        run: echo ${{ steps.docker_build_push.outputs.digest }}

      - name: Move Docker Layer Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
